create table AGENDAMENTOS (
    AGENDAMENTO_ID        number generated by default as identity primary key,
    NOME                  varchar2(50) not null,
    OBSERVACAO            varchar2(400),
    CLIENTE_ID            number not null,
    ATENDENTE_ID          number not null,
    DATA_AGENDAMENTO      DATE,
    
    constraint FK_CLIENTE_AGENDAMENTO foreign key (CLIENTE_ID)
        references CLIENTES (CLIENTE_ID),

    constraint FK_ATENDENTE_AGENDAMENTO foreign key (ATENDENTE_ID)
        references CLIENTES (CLIENTE_ID)
);

--mysql

create table AGENDAMENTOS (
    AGENDAMENTO_ID        int auto_increment primary key,
    NOME                  varchar(50) not null,
    OBSERVACAO            varchar(400),
    CLIENTE_ID            int not null,
    ATENDENTE_ID          int not null,
    DATA_AGENDAMENTO      datetime,
    
    constraint FK_CLIENTE_AGENDAMENTO foreign key (CLIENTE_ID)
        references CLIENTES (CLIENTE_ID),

    constraint FK_ATENDENTE_AGENDAMENTO foreign key (ATENDENTE_ID)
        references CLIENTES (CLIENTE_ID)
);