create table CLIENTES (
  CLIENTE_ID      number generated by default as identity primary key,
  NOME            varchar2(100) not null,
  DATA_NASCIMENTO date,
  STATUS          varchar(10) default 'ativo' not null,
  CPF_CNPJ        varchar2(14),
  
  TELEFONE      varchar2(16),
  EMAIL         varchar2(50),
  DATA_CADASTRO date default sysdate not null,
  LIMITE        number(10,2) default 0 not null,
  FORMA_PAGAMENTO_PADRAO varchar2(20),
  
  ENDEbairroRECO    varchar(30),
  BAIRRO      varchar(20),
  CIDADE      varchar(23),
  UF          varchar(2),
  CEP         varchar(9),
    
  constraint CK_CLIENTE_CEP check (regexp_like(CEP, '^[0-9]{5}-[0-9]{3}$')),
  constraint CK_CLIENTE_STATUS check (STATUS in ('ATIVO','INATIVO'))
)